# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_constraint.xdc

# Block Designs: bd/design_awg/design_awg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg || ORIG_REF_NAME==design_awg} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_microblaze_0_1/design_awg_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_microblaze_0_1 || ORIG_REF_NAME==design_awg_microblaze_0_1} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_dlmb_v10_2/design_awg_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_dlmb_v10_2 || ORIG_REF_NAME==design_awg_dlmb_v10_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_ilmb_v10_2/design_awg_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_ilmb_v10_2 || ORIG_REF_NAME==design_awg_ilmb_v10_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_dlmb_bram_if_cntlr_2/design_awg_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_awg_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_ilmb_bram_if_cntlr_2/design_awg_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_awg_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_lmb_bram_2/design_awg_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_lmb_bram_2 || ORIG_REF_NAME==design_awg_lmb_bram_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_mdm_1_2/design_awg_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_mdm_1_2 || ORIG_REF_NAME==design_awg_mdm_1_2} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_clk_wiz_1_1/design_awg_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_clk_wiz_1_1 || ORIG_REF_NAME==design_awg_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_rst_clk_wiz_1_100M_1/design_awg_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_awg_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_awg_axi_0_0/design_awg_awg_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_awg_axi_0_0 || ORIG_REF_NAME==design_awg_awg_axi_0_0} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_xbar_1/design_awg_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_xbar_1 || ORIG_REF_NAME==design_awg_xbar_1} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_microblaze_0_axi_periph_1/design_awg_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_awg_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_awg/ip/design_awg_axi_uartlite_0_0/design_awg_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_awg_axi_uartlite_0_0 || ORIG_REF_NAME==design_awg_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_microblaze_0_1/design_awg_microblaze_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_microblaze_0_1 || ORIG_REF_NAME==design_awg_microblaze_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_microblaze_0_1/design_awg_microblaze_0_1_ooc_debug.xdc

# XDC: bd/design_awg/ip/design_awg_microblaze_0_1/design_awg_microblaze_0_1_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_dlmb_v10_2/design_awg_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_dlmb_v10_2 || ORIG_REF_NAME==design_awg_dlmb_v10_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_dlmb_v10_2/design_awg_dlmb_v10_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_ilmb_v10_2/design_awg_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_ilmb_v10_2 || ORIG_REF_NAME==design_awg_ilmb_v10_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_ilmb_v10_2/design_awg_ilmb_v10_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_dlmb_bram_if_cntlr_2/design_awg_dlmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_ilmb_bram_if_cntlr_2/design_awg_ilmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_lmb_bram_2/design_awg_lmb_bram_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_mdm_1_2/design_awg_mdm_1_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_mdm_1_2 || ORIG_REF_NAME==design_awg_mdm_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_mdm_1_2/design_awg_mdm_1_2_ooc_trace.xdc

# XDC: bd/design_awg/ip/design_awg_mdm_1_2/design_awg_mdm_1_2_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_clk_wiz_1_1/design_awg_clk_wiz_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_clk_wiz_1_1 || ORIG_REF_NAME==design_awg_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_clk_wiz_1_1/design_awg_clk_wiz_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_clk_wiz_1_1 || ORIG_REF_NAME==design_awg_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_clk_wiz_1_1/design_awg_clk_wiz_1_1_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_rst_clk_wiz_1_100M_1/design_awg_rst_clk_wiz_1_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_awg_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_rst_clk_wiz_1_100M_1/design_awg_rst_clk_wiz_1_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_awg_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_rst_clk_wiz_1_100M_1/design_awg_rst_clk_wiz_1_100M_1_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_xbar_1/design_awg_xbar_1_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_axi_uartlite_0_0/design_awg_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_axi_uartlite_0_0 || ORIG_REF_NAME==design_awg_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/ip/design_awg_axi_uartlite_0_0/design_awg_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_awg/ip/design_awg_axi_uartlite_0_0/design_awg_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_awg_axi_uartlite_0_0 || ORIG_REF_NAME==design_awg_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_awg/design_awg_ooc.xdc
